In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

In [17]:
X=tf.placeholder(tf.float32,shape=[None ,3])
Y=tf.placeholder(tf.float32, shape=[None,1])

In [14]:
xy = np.loadtxt('C:\교육\인공지능 강의_소프트웨어인재개발원\김성훈교수님\실습자료_이재오\scoreData.csv', delimiter=',', dtype=np.float32)
print(xy)

[[  73.   80.   75.  152.]
 [  93.   88.   93.  185.]
 [  89.   91.   90.  180.]
 [  96.   98.  100.  196.]
 [  73.   66.   70.  142.]
 [  53.   46.   55.  101.]]


In [18]:
#두개의 traing 을 위한 변수 선언
W= tf.Variable(tf.random_normal([3,1]),name='weight')
b= tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W)+b

In [16]:
x_data=xy[:,0:-1]
y_data=xy[:,[-1]]
print(x_data)
print(y_data)

[[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]]
[[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]


In [27]:
#cost/lost function
cost = tf.reduce_mean(tf.square(hypothesis -Y))


In [15]:
#미분을 이용하는 gradient decent를 이용하여 최소화
learning_rate =0.1
gradient = tf.reduce_mean((W*X -Y)*X) 
decent = W -learning_rate*gradient
update = W.assign(decent)

In [20]:
#Minimize
Optimizer = tf.train.GradientDescentOptimizer(learning_rate =0.000001)
train= Optimizer.minimize(cost)

In [21]:
sess =tf.Session()
sess.run(tf.global_variables_initializer())

In [30]:
W_val=[]
const_val=[]

In [23]:
for step in range(2001):
    cost_val,hy_val,_= sess.run([cost,hypothesis,train],feed_dict={X:x_data,Y:y_data})
    if step %20 == 0:
        print(step,"COST:",cost_val,"prediction :", hy_val)
#plt.plot =(W_val,cost_val)
#plt.show()



0 COST: 9.72057 prediction : [[ 148.20909119]
 [ 185.70150757]
 [ 178.9927063 ]
 [ 194.61050415]
 [ 144.01902771]
 [ 107.03643036]]
20 COST: 9.70921 prediction : [[ 148.2118988 ]
 [ 185.70005798]
 [ 178.99382019]
 [ 194.61114502]
 [ 144.01719666]
 [ 107.03366089]]
40 COST: 9.69788 prediction : [[ 148.2147522 ]
 [ 185.69873047]
 [ 178.99499512]
 [ 194.6118927 ]
 [ 144.01542664]
 [ 107.03092957]]
60 COST: 9.68657 prediction : [[ 148.21763611]
 [ 185.69740295]
 [ 178.99623108]
 [ 194.61265564]
 [ 144.01368713]
 [ 107.02822876]]
80 COST: 9.67527 prediction : [[ 148.22052002]
 [ 185.69607544]
 [ 178.99742126]
 [ 194.61341858]
 [ 144.01193237]
 [ 107.02552795]]
100 COST: 9.664 prediction : [[ 148.22338867]
 [ 185.69476318]
 [ 178.99862671]
 [ 194.61418152]
 [ 144.01020813]
 [ 107.02281952]]
120 COST: 9.65273 prediction : [[ 148.22622681]
 [ 185.69338989]
 [ 178.99978638]
 [ 194.61489868]
 [ 144.00842285]
 [ 107.02009583]]
140 COST: 9.6415 prediction : [[ 148.22904968]
 [ 185.69200134]
 [ 179

1400 COST: 8.9624 prediction : [[ 148.40365601]
 [ 185.60768127]
 [ 179.07234192]
 [ 194.65931702]
 [ 143.89707947]
 [ 106.84931946]]
1420 COST: 8.95202 prediction : [[ 148.40635681]
 [ 185.6063385 ]
 [ 179.07342529]
 [ 194.65995789]
 [ 143.89535522]
 [ 106.84667206]]
1440 COST: 8.94172 prediction : [[ 148.40905762]
 [ 185.60502625]
 [ 179.07450867]
 [ 194.66064453]
 [ 143.89364624]
 [ 106.84406281]]
1460 COST: 8.93143 prediction : [[ 148.41177368]
 [ 185.60374451]
 [ 179.07565308]
 [ 194.66133118]
 [ 143.89195251]
 [ 106.84146881]]
1480 COST: 8.92115 prediction : [[ 148.41447449]
 [ 185.60243225]
 [ 179.07675171]
 [ 194.66200256]
 [ 143.89025879]
 [ 106.83885956]]
1500 COST: 8.91087 prediction : [[ 148.41717529]
 [ 185.60112   ]
 [ 179.07785034]
 [ 194.66267395]
 [ 143.8885498 ]
 [ 106.83625031]]
1520 COST: 8.90062 prediction : [[ 148.41984558]
 [ 185.59977722]
 [ 179.07893372]
 [ 194.66331482]
 [ 143.88682556]
 [ 106.83363342]]
1540 COST: 8.89035 prediction : [[ 148.42253113]
 [ 185.