In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
with tf.variable_scope('one_cell') as scope:
    # One cell RNN input_dim (4) -> output_dim (2)
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)

    x_data = np.array([[h]], dtype=np.float32) # x_data = [[[1,0,0,0]]]
    pp.pprint(x_data)
    #outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

    sess.run(tf.global_variables_initializer())
    #pp.pprint(outputs.eval())
    

2 2
array([[[ 1.,  0.,  0.,  0.]]], dtype=float32)


In [4]:
with tf.variable_scope('two_sequences') as scope:
    hidden_size=2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data=np.array([h,e,l,l,o],dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    #outputs,_states =tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    outputs,_states= tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(5, 4)
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)


ValueError: Shape (4, 5) must have rank at least 3

In [6]:
with tf.variable_scope('3_batch') as scope:
    x_data=np.array([[h,e,l,l,o],
                    [e,o,l,l,l],
                    [l,l,e,e,l]], dtype=np.float32)
    pp.pprint(x_data)
    hidden_size =2
    cell= rnn.BasicLSTMCell(num_units=hidden_size,state_is_tuple=True)
    outputs,_states= tf.nn.dynamic_rnn(cell,x_data,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)


ValueError: Variable 3_batch/rnn/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)


In [7]:
with tf.variable_scope('batch_dynamic_length') as scope:
    x_data=np.array([[h,e,l,l,o],
           [e,o,l,l,l],
           [l,l,e,e,l]], dtype=np.float32)
    pp.pprint(x_data)
    hidden_size =2
    cell=rnn.BasicLSTMCell(num_units=hidden_size,state_is_tuple=True)
    outputs,_states=tf.nn.dynamic_rnn(cell,x_data,sequence_length=[5,3,4],dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())
    

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[-0.07163873,  0.00073005],
        [ 0.09679924,  0.03802459],
        [ 0.09706102,  0.11405468],
        [ 0.07503138,  0.15659679],
        [ 0.03368411,  0.18256094]],

       [[ 0.14372706,  0.03742975],
        [ 0.10440707,  0.11201001],
        [ 0.09358499,  0.15851146],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[-0.01535471,  0.08322863],
        [-0.02640496,  0.13917747],
        [ 0.12816842,  0.11445395],
        [ 0.23502685,  0.11925853],
        [ 0.        ,

In [9]:
with tf.variable_scope ('initial_State') as scope:
    batch_size =3
    x_data=np.array([[h,e,l,l,o],
                    [e,o,l,l,l],
                    [l,l,e,e,l]], dtype=np.float32)
    pp.pprint(x_data)
    hidden_size =2
    cell= rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple= True)
    initial_state= cell.zero_state(batch_size, tf.float32)
    outputs,_states=tf.nn.dynamic_rnn(cell,x_data,
                                     initial_state=initial_state,dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.11082888, -0.19332321],
        [ 0.17035551, -0.18055008],
        [ 0.20072968, -0.28751883],
        [ 0.23470415, -0.35983545],
        [ 0.19609314, -0.16972955]],

       [[ 0.06866204, -0.01268665],
        [ 0.10305031,  0.14697422],
        [ 0.21346034, -0.071394  ],
        [ 0.24935704, -0.21575779],
        [ 0.26638818, -0.31126407]],

       [[ 0.1214006 , -0.18426444],
        [ 0.18990244, -0.29662007],
        [ 0.25929666, -0.27891332],
        [ 0.27848393, -0.23812577],
        [ 0.25258031,

In [12]:
batch_size=3
sequence_length=5
intput_dim=3

x_data=np.array(45,dtype=np.float32).reshape(batch_size,sequence_length, intput_dim)
pp.pprint(x_data)

ValueError: cannot reshape array of size 1 into shape (3,5,3)

In [14]:
with tf.variable_scope('general_data') as scope:
    cell= rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
    initial_state= cell.zero_state(batch_size,tf.float32)
    outputs,_states= tf.nn.dynamic_rnn(cell,x_data,
                                      initial_state=initial_state, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    
    pp.pprint(outputs.eval())

array([[[-0.10128586, -0.03233699, -0.06051519, -0.08724802, -0.10866513],
        [-0.13789384,  0.01596529, -0.08620656, -0.13061105, -0.0265412 ],
        [-0.07350691, -0.04741864, -0.16237631, -0.08030067, -0.07666829],
        [-0.02658907, -0.08548237, -0.21561931, -0.03861503, -0.11294336],
        [ 0.09055164, -0.00439766, -0.15704757, -0.04387873, -0.01557733]],

       [[-0.05508732,  0.05331376, -0.04817985, -0.07629956,  0.03470935],
        [ 0.06721017,  0.08895062, -0.07652687, -0.08204232,  0.07651389],
        [ 0.06189355,  0.01292723, -0.17638202, -0.06725397,  0.01683637],
        [ 0.06122844, -0.03992843, -0.22589445, -0.02916943, -0.04188945],
        [ 0.06551666, -0.07446368, -0.25512522,  0.01415245, -0.08696672]],

       [[ 0.00222846, -0.03227051, -0.10705683,  0.0078711 , -0.04310934],
        [ 0.0162657 , -0.06042758, -0.17991848,  0.0285959 , -0.08149347],
        [-0.01924969, -0.00951066, -0.18544127, -0.03358711, -0.02833066],
        [-0.04424337,

In [16]:
with tf.variable_scope('MultiRNNCell') as scope:
    cell=rnn.BasicLSTMCell(num_units=5,state_is_tuple= True)
    cell=rnn.MultiRNNCell([cell]*3, state_is_tuple= True)
    
    outputs,_states=tf.nn.dynamic_rnn(cell,x_data, dtype=tf.float32)
    print("dynamic rnn:",outputs)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

ValueError: Variable MultiRNNCell/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)


In [17]:
with tf.variable_scope("dynamic_rnn") as scope:
    cell=rnn.BasicLSTMCell(num_units=5,state_is_tuple=  True)
    outputs,_states= tf.nn.dynamic_rnn(cell,x_data, dtype=tf.float32,
                                      sequence_length=[1,3,2])
    
    print("dynamic rnn", outputs)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

dynamic rnn Tensor("dynamic_rnn/rnn/transpose:0", shape=(3, 5, 5), dtype=float32)
array([[[-0.1030066 , -0.00290079,  0.01018988,  0.05763286,  0.05742789],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],

       [[-0.02806741,  0.02518125, -0.03362552,  0.13274416, -0.01216885],
        [ 0.03091399,  0.0711517 , -0.08837115,  0.15897767,  0.10698328],
        [ 0.04630169,  0.0260718 ,  0.02080088,  0.04250322,  0.0349267 ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],

       [[ 0.04986085, -0.04580278,  0.09091046, -0.10822277, -0.04794835],
        [ 0.10124478, -0.09883711,  0.14510238, -0.18683635, -0.09683379],
        [ 0.  

In [20]:
with tf.variable_scope("bi_directional") as scope:
        cell_fw=rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
        cell_bw=rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
        
        outputs,states= tf.nn.bidirectional_dynamic_rnn(cell_fw,cell_bw,x_data,
                                                       sequence_length= [2,3,1],
                                                       dtype=tf.float32)
        sess.run(tf.global_variables_initializer())
        
        pp.pprint(sess.run(outputs))
        pp.pprint(sess.run(states))

ValueError: Variable bi_directional/bidirectional_rnn/fw/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)


In [22]:
hidden_size=3
sequence_length =5
batch_size=3
num_classes =5

pp.pprint(x_data)
x_data=x_data.reshape(-1,hidden_size)
pp.pprint(x_data)

softmax_w= np.array(15,dtype=np.float32).reshape(hidden_size, num_classes)
outputs=np.matmul(x_data,softmax_w)
outputs= outputs.reshape(-1,sequence_length, num_classes)
pp.pprint(outputs)

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.]], dtype=float32)
array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  1.,  0.]], dtype=float32)


ValueError: cannot reshape array of size 1 into shape (3,5)

In [28]:
y_data=tf.constant([[1,1,1]])

prediction=tf.constant([[[0.2,0.7],[0.6, 0.2],[0.2,0.9]]],dtype=tf.float32)

weights=tf.constant([[1,1,1]], dtype=tf.float32)

sequence_loss=tf.contrib.seq2seq.sequence_loss(logits=prediction, targets=y_data, weights= weights)
sess.run(tf.global_variables_initializer())
print("Loss:", sequence_loss.eval())

Loss: 0.596759


In [31]:
y_data=tf.constant([[1,1,1]])


prediction1=tf.constant([[[0.3,0.7],[0.3,0.7],[0.3,0.7]]], dtype= tf.float32)
prediction2=tf.constant([[[0.1,0.9],[0.1,0.9],[0.1,0.9]]], dtype= tf.float32)

prediction3 = tf.constant([[[1, 0], [1, 0], [1, 0]]], dtype=tf.float32)
prediction4 = tf.constant([[[0, 1], [1, 0], [0, 1]]], dtype=tf.float32)

weights=tf.constant([[1,1,1]], dtype= tf.float32)

seqeuence_loss1=tf.contrib.seq2seq.sequence_loss(prediction1,y_data,weights)
seqeuence_loss2=tf.contrib.seq2seq.sequence_loss(prediction2,y_data,weights)
seqeuence_loss3=tf.contrib.seq2seq.sequence_loss(prediction3,y_data,weights)
seqeuence_loss4=tf.contrib.seq2seq.sequence_loss(prediction4,y_data,weights)

sess.run(tf.global_variables_initializer())
print("Loss1:" ,seqeuence_loss1.eval(),
     "Loss2:",seqeuence_loss2.eval(),
     "Loss3:", seqeuence_loss3.eval(),
     "Loss4:", seqeuence_loss4.eval())


Loss1: 0.513015 Loss2: 0.371101 Loss3: 1.31326 Loss4: 0.646595
